#!/bin/bash

function svn() {
  command svn "$@" | awk '
  BEGIN {
    cpt_c=0;
  }
  {
    if        ($1=="C") {
      cpt_c=cpt_c+1;
      print "\033[35m" $0 "\033[00m";  # Conflicts
    }
    else if   ($1=="A") {
      print "\033[32m" $0 "\033[00m";  # Add in green
    }
    else if   ($1=="?") {
      print "\033[36m" $0 "\033[00m";  # New in cyan
    }
    else if   ($1=="D") {
      print "\033[31m" $0 "\033[00m";  # Deletes
    }
    else                {
      print $0;                        # No color, just print the line
    }
  }
  END {
    print cpt_c, " conflicts are found.";
  }';
}

function svn-whatchanged() {
  svn log -v | less
}

function svn-diff() {
  svn diff $@ | colordiff | less
}

function svn-show() {
  svn-diff -c $1
}

function svn-log() {
  svn log | less
}

function svn-authors() {
  svn log -v --xml | grep '<author.*/author>' | sort $* | uniq -c | sort -rn | sed -e "s/\<author\>//g" | sed -e "s/\<\/author\>//g"
}
