#!/bin/bash

function add_file_status_color() {
  awk '
  BEGIN {
    cpt_c=0;
  }
  {
    if        ($1=="C") {
      cpt_c=cpt_c+1;
      print "\033[35m" $0 "\033[00m";  # Conflicts
    }
    else if   ($1=="A") {
      print "\033[32m" $0 "\033[00m";  # Add in green
    }
    else if   ($1=="?") {
      print "\033[36m" $0 "\033[00m";  # New in cyan
    }
    else if   ($1=="D") {
      print "\033[31m" $0 "\033[00m";  # Deletes
    }
    else                {
      print $0;                        # No color, just print the line
    }
  }
  END {
    print cpt_c, " conflicts are found.";
  }';
}

function svn_whatchanged() {
  command svn log -v | add_file_status_color | less
}

function svn_diff() {
  command svn diff $@ | colordiff | less
}

function svn_show() {
  svn_diff -c $1
}

function svn_log() {
  command svn log | less
}

function svn_st() {
  command svn st | add_file_status_color
}

function svn_authors() {
  command svn log -v --xml |
    grep '<author.*/author>' |
    sort $* |
    uniq -c |
    sort -rn |
    sed -e "s/\<author\>//g" |
    sed -e "s/\<\/author\>//g"
}

function svn() {
  cmd=$1;
  if type "svn_"$cmd > /dev/null 2>&1; then
    shift
    "svn_"$cmd $@
  else
    command svn $@
  fi
}
