#!/bin/bash

function add_file_status_color() {
  awk '
  {
    if ($1=="C") {
      print "\033[35m" $0 "\033[00m";
    }
    else if ($1=="A") {
      print "\033[32m" $0 "\033[00m";
    }
    else if ($1=="?") {
      print "\033[36m" $0 "\033[00m";
    }
    else if ($1=="D") {
      print "\033[31m" $0 "\033[00m";
    }
    else {
      print $0;
    }
  }';
}

function svn_whatchanged() {
  command svn log -v | add_file_status_color | less
}

function svn_diff() {
  command svn diff $@ | colordiff | less
}

function svn_show() {
  svn_diff -c $@
}

function svn_log() {
  command svn log | less
}

function svn_st() {
  command svn st $@ | add_file_status_color
}

function svn_up() {
  command svn up $@ | add_file_status_color
}

function svn_revert-rev() {
  command svn diff -c $@ . | patch -R -p0
}

function svn_authors() {
  command svn log -v --xml |
    grep '<author.*/author>' |
    sort $* |
    uniq -c |
    sort -rn |
    sed -e "s/\<author\>//g" |
    sed -e "s/\<\/author\>//g"
}

function svn() {
  cmd=$1;
  if type "svn_"$cmd > /dev/null 2>&1; then
    shift
    "svn_"$cmd $@
  else
    command svn $@
  fi
}
